apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wg7uv8c76-python
  janus-idp.io/tekton: wg7uv8c76-python
  backstage.io/kubernetes-id: wg7uv8c76-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wg7uv8c76-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
